# Generated by Django 5.1.7 on 2025-03-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_size_tovar_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='size',
        ),
        migrations.AddField(
            model_name='tovar',
            name='size',
            field=models.ManyToManyField(to='app.size'),
        ),
    ]
