# Generated by Django 5.1.7 on 2025-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tovar_size_tovar_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='size',
            field=models.ManyToManyField(to='app.size', verbose_name='Размер'),
        ),
    ]
